import express from 'express';
import http from 'http';
import { Server } from 'socket.io';
import cors from 'cors';
import gameSocket from './sockets/gameSocket.js';
import apiRoutes from './routes/api.js';
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api', apiRoutes);
app.get('/health', (req, res) => res.json({ ok: true }));
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: '*' } });
gameSocket(io);
const PORT = process.env.PORT || 4000;
server.listen(PORT, () => console.log(`Backend listening on ${PORT}`));
